name: Minecraft Server

on:
  workflow_dispatch:  # 手动触发

jobs:
  mc-server:
    runs-on: ubuntu-latest

    steps:
      # 1. 安装 Java 17（推荐使用官方 action）
      - name: 设置 Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 2. 获取最新的 PaperMC 版本和构建号
      - name: 获取 PaperMC 最新版本
        id: paper
        run: |
          # 获取最新版本号
          PAPER_VERSION=1.20.1
          echo "最新版本: $PAPER_VERSION"

          # 获取该版本的最新构建号
          PAPER_BUILD=$(curl -s "https://api.papermc.io/v2/projects/paper/versions/$PAPER_VERSION/builds" | jq -r '.builds[-1].build')
          echo "最新构建号: $PAPER_BUILD"

          # 输出变量供后续步骤使用
          echo "PAPER_VERSION=$PAPER_VERSION" >> $GITHUB_OUTPUT
          echo "PAPER_BUILD=$PAPER_BUILD" >> $GITHUB_OUTPUT

      # 3. 下载 PaperMC 服务端
      - name: 下载 PaperMC
        run: |
          wget "https://api.papermc.io/v2/projects/paper/versions/${{ steps.paper.outputs.PAPER_VERSION }}/builds/${{ steps.paper.outputs.PAPER_BUILD }}/downloads/paper-${{ steps.paper.outputs.PAPER_VERSION }}-${{ steps.paper.outputs.PAPER_BUILD }}.jar" -O server.jar

      # 4. 同意 EULA 协议
      - name: 同意 EULA
        run: echo "eula=true" > eula.txt

      # 5. 启动 playit.gg 隧道
      - name: 启动 playit.gg 隧道
        run: |
           wget "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64" -O playit
           chmod +x playit
           echo "yes" | ./playit --accept-license

      # 6. 启动 Minecraft 服务器
      - name: 启动 Minecraft 服务器
        run: |
          echo "你可以使用以下地址连接服务器："
          echo "${{ env.PLAYIT_URL }}"
          java -Xmx2G -Xms1G -jar server.jar nogui
        timeout-minutes: 360  # 最多运行 6 小时
