name: Minecraft Server

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  mc-server:
    runs-on: ubuntu-latest
    steps:
      # 1. 安装 Java 环境
      - name: 安装 Java 17
        run: sudo apt-get install -y openjdk-17-jdk

      # 2. 下载 PaperMC 服务端（以 1.20.4 为例）
      - name: 下载 PaperMC
        run: |
          PAPER_VERSION="1.20.4"
          wget "https://api.papermc.io/v2/projects/paper/versions/${PAPER_VERSION}/builds/latest/downloads/paper-${PAPER_VERSION}-latest.jar" -O server.jar

      # 3. 同意 EULA 协议
      - name: 同意 EULA
        run: echo "eula=true" > eula.txt

      # 4. 安装 Ngrok 并暴露 25565 端口
      - name: 设置 Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}  # 从 GitHub Secrets 读取 Token
          ngrok tcp 25565 --log=stdout > ngrok.log &  # 后台运行 Ngrok
          sleep 10  # 等待 Ngrok 启动

      # 5. 获取 Ngrok 公网地址并输出
      - name: 获取连接地址
        run: |
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "================================"
          echo "连接地址: ${NGROK_URL}"
          echo "================================"

      # 6. 启动服务器（最大运行 6 小时）
      - name: 启动 Minecraft 服务器
        run: |
          java -Xmx2G -Xms1G -jar server.jar nogui  # 分配 2GB 内存
        timeout-minutes: 360  # GitHub Actions 最长允许运行 6 小时
