name: Minecraft Server

on:
  workflow_dispatch:  # 手动触发

jobs:
  mc-server:
    runs-on: ubuntu-latest
    steps:
      # 1. 安装 Java 17
      - name: 安装 Java 17
        run: sudo apt-get install -y openjdk-17-jdk

      # 2. 动态获取最新 PaperMC 版本和构建号
      - name: 获取 PaperMC 最新版本
        id: paper
        run: |
          # 获取最新版本号（例如 1.20.4）
          PAPER_VERSION=1.20.1
          echo "最新版本: $PAPER_VERSION"

          # 获取该版本的最新构建号
          PAPER_BUILD=$(curl -s "https://api.papermc.io/v2/projects/paper/versions/$PAPER_VERSION/builds" | jq -r '.builds[-1].build')
          echo "最新构建号: $PAPER_BUILD"

          # 输出变量供后续步骤使用
          echo "PAPER_VERSION=$PAPER_VERSION" >> $GITHUB_OUTPUT
          echo "PAPER_BUILD=$PAPER_BUILD" >> $GITHUB_OUTPUT

      # 3. 下载 PaperMC 服务端
      - name: 下载 PaperMC
        run: |
          wget "https://api.papermc.io/v2/projects/paper/versions/${{ steps.paper.outputs.PAPER_VERSION }}/builds/${{ steps.paper.outputs.PAPER_BUILD }}/downloads/paper-${{ steps.paper.outputs.PAPER_VERSION }}-${{ steps.paper.outputs.PAPER_BUILD }}.jar" -O server.jar

      # 4. 同意 EULA 协议
      - name: 同意 EULA
        run: echo "eula=true" > eula.txt

      # 5. 使用 playit.gg 暴露端口
      - name: 启动 playit.gg 隧道
        run: |
          # 下载 playit.gg
          wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64 -O playit
          chmod +x playit

          # 自动同意协议并启动隧道
          echo "yes" | ./playit --accept-license &  # 后台运行
          sleep 30  # 等待隧道启动

          # 从日志中提取连接地址
          PLAYIT_URL=$(grep -o "game started at: tcp://playit-host:[0-9]*" playit.log | sed 's/game started at: //')
          echo "================================"
          echo "连接地址: $PLAYIT_URL"
          echo "================================"======================="

      # 7. 启动服务器
      - name: 启动 Minecraft 服务器
        run: |
          java -Xmx2G -Xms1G -jar server.jar nogui
        timeout-minutes: 360  # 6 小时限制
